<?php

// This file is not generated by default. We create it to save our Plivo Credentials.
// So we can use theme when needed.
return [
    'credentials' => [
        'auth_id' => 'MAMGI1Y2Q1M2U2Y2FKYW',
        'auth_token' => 'M2Y5YzQ3OTlmNzM3MTUyZTY2ZWQ1MDA2MDhkMzI5'
    ],
];